import type { Metadata } from "next";
import { Inter, Lusitana } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const lusitana = Lusitana({
  variable: "--font-lusitana",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Practice Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lusitana.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
